### ISSUE TITLE
Issue with the house rename menu

### ISSUE THREAD

**Issue by Brooksiito** [Melrpm/Resmurf-Housing-System#2]
Hey men, 
I will try to install your script on my server but an issue is little bit strange..
It's really impossible to accept or cancel the name of the house..
Do you have any solution ?
![image](https://user-images.githubusercontent.com/78375212/115772906-f5994900-a3af-11eb-8a8d-d9833472f624.png)
@Melrpm @MasiBall

**Comment by HezimX** [comment]
Did you rename the script to properties?

**Comment by Brooksiito** [comment]
> Did you rename the script to properties?

thank you bro

**Comment by Brooksiito** [comment]
Do you have an idea of the reason of this ? 
![image](https://user-images.githubusercontent.com/78375212/115859845-fb833e80-a430-11eb-8263-8b6d7a4260eb.png)
@Melrpm @MasiBall

**Comment by HezimX** [comment]
> Do you have an idea of the reason of this ?
> ![image](https://user-images.githubusercontent.com/78375212/115859845-fb833e80-a430-11eb-8263-8b6d7a4260eb.png)
> @Melrpm @MasiBall

When dose it happen havent seen that befor

**Comment by Morbe17** [comment]
Hi Hezim,

That's probably a console.log in the JS file. I will proceed to delete it now. You may delete anything in your html/index.js that ha console.log to prevent it from pushing it to the DB or download the latest JS.
